# -*- coding: utf-8 -*-
"""0725.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HdF_S4Hf7rN9xvrm5Vft9e22fJGqk52X
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/digitalhana/NLP/청원_data/train.csv')
df.head()

df['category'].value_counts()

